### ISSUE TITLE
Unrecoverable crash into safe mode when calling wifi.radio.start_ap on ESP32-S3-BOX-Lite

### ISSUE THREAD

**Issue by sean-palmer-coding** [adafruit/circuitpython#7254]
### CircuitPython version

```python
adafruit-circuitpython-espressif_esp32s3_box_lite-en_US-8.0.0-beta; ESP32-S3-BOX-Lite
```

### Code/REPL

```python
import wifi

wifi.radio.start_ap("esp32", "password123")
```

### Behavior

Board disconnects from serial connection, when code above input into REPL, it returns:

```Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
Internal watchdog timer expired.



### Description

_No response_

### Additional information

_No response_

**Comment by sean-palmer-coding** [comment]
This seems to fail when just trying to connect to an AP as well.

```wifi.radio.connect("ssid", "password")```

**Comment by tannewt** [comment]
What beta are you using? Please also try the absolute latest build to see if this has been fixed already. Thanks!

**Comment by dhalbert** [comment]
This is a BOX Lite board. I fixed the regular BOX, but I don't have a Box Lite to test.

**Comment by tannewt** [comment]
I think @makermelissa has a box lite.

**Comment by sean-palmer-coding** [comment]
Just flashed the latest circuit python build available on the S3 bucket (adafruit-circuitpython-espressif_esp32s3_box_lite-en_US-20221203-a50b0a2), still the same issue.

**Comment by dhalbert** [comment]
I got a BOX Lite on Friday and will be testing this.
