### ISSUE TITLE
RGB Matrix content not displaying correctly on CircuitPython 8.2.3

### ISSUE THREAD

**Issue by phantomsixthplayer** [adafruit/circuitpython#8303]
### CircuitPython version

```python
Working:
Adafruit CircuitPython 8.2.2 on 2023-07-31; Adafruit Grand Central M4 Express with samd51p20
Board ID:grandcentral_m4_express

Not working:
Adafruit CircuitPython 8.2.3 on 2023-08-11; Adafruit Grand Central M4 Express with samd51p20
Board ID:grandcentral_m4_express


UF2 Bootloader v3.15.0 SFHWRO
Model: Grand Central M4 Express
Board-ID: SAMD51P20A-GrandCentral-v0

adafruit-circuitpython-bundle-8.x-mpy-20230824
```

### Code/REPL

```python
import displayio
import rgbmatrix
import board
import framebufferio
from adafruit_bitmap_font import bitmap_font
from adafruit_display_text.label import Label
import digitalio
import busio
import sdcardio
import storage
import adafruit_debouncer

displayio.release_displays()

matrix = rgbmatrix.RGBMatrix(
    width=64,
    height=32,
    bit_depth=4,
    rgb_pins=[board.D8, board.D9, board.D10, board.D11, board.D12, board.D13],
    addr_pins=[board.D4, board.D6, board.D3, board.D5],
    clock_pin=board.D1,
    latch_pin=board.D2,
    output_enable_pin=board.D0
)
display = framebufferio.FramebufferDisplay(matrix)

font = bitmap_font.load_font("/fonts/test.pcf")

mg = displayio.Group()
mg_a = Label(font, text="A.A.A.A", color=0x00FF00, x=15, y=6)
mg_h = Label(font, text="H.H.H.H", color=0x00FF00, x=14, y=17)
mg_b = Label(font, text="B.B.B.B", color=0x00FF00, x=15, y=28)
mg.append(mg_a)
mg.append(mg_h)
mg.append(mg_b)

class HiscoreController:
    def __init__(self):
        spi = busio.SPI(board.SD_SCK, board.SD_MOSI, board.SD_MISO)
        sdcard = sdcardio.SDCard(spi, board.SD_CS)
        vfs = storage.VfsFat(sdcard)
        storage.mount(vfs, "/")

    def hiscore(self, value=-1):
        if value >= 0:
            try:
                with open("/hiscore.txt", "w") as hiscore_file:
                    if value > 9999:
                        hiscore_file.write(str(value - 10000))
                    else:
                        hiscore_file.write(str(value))
            except OSError:
                pass
        else:
            if "hiscore.txt" in os.listdir("/"):
                try:
                    with open("/hiscore.txt", "r") as hiscore_file:
                        score = hiscore_file.read()
                        return score
                except OSError:
                    pass

class ButtonController:
    def __init__(self, btns_and_names):
        self.buttons = {}

        for name, btn in btns_and_names.items():
            button_pin = digitalio.DigitalInOut(btn["obj"])
            button_pin.switch_to_input(pull=digitalio.Pull.UP)
            self.buttons[name] = adafruit_debouncer.Debouncer(button_pin)

    def is_pressed(self, btn_name):
        return self.buttons[btn_name].fell

    def reset(self):
        for btn in self.buttons.values():
            btn.update()

    def update(self):
        for btn in self.buttons.values():
            btn.update()

hiscore_ctrl = HiscoreController()

buttons = ButtonController(
    btns_and_names = {
        "reset": {"num": 1, "obj": board.D27}
    }
)

def menu(screen_state):
    reset = False

    display.show(mg)

    buttons.reset()

    while screen_state == menu:
        buttons.update()

        if buttons.is_pressed("reset"):
            hiscore_ctrl.hiscore(value=0)
            reset = True

screens = {
    menu: menu
}

screen_state = menu

while True:
    current_screen = screens[screen_state]
    screen_state = current_screen(screen_state)
```

### Behavior

When I run CircuitPython 8.2.2, the RGB Matrix displays content correctly.

https://github.com/adafruit/circuitpython/assets/22541984/74018af0-e5d5-4bdc-997f-600f1dd09850

When I run CircuitPython 8.2.3, the RGB Matrix displays content incorrectly.

https://github.com/adafruit/circuitpython/assets/22541984/d46d3e68-794c-4598-8ccc-62a310ed17ae

**Comment by dhalbert** [comment]
@phantomsixthplayer Could you describe where you got the RGB matrices, with a link too? are they from us? If so, could you take photos of the box label(s), so we can see the batch?

**Comment by phantomsixthplayer** [comment]
@dhalbert I got my RGB matrices all from https://www.digikey.com.au/en/products/detail/adafruit-industries-llc/2278/7035036

For the RGB Matrix in the videos. I don't have the original box.
![rgb_matrix_shown_in_videos](https://github.com/adafruit/circuitpython/assets/22541984/3648f0d0-e6bb-4602-b1cd-dc6c7778252f)

I do have another two spares I haven't tested yet.

![matrix_spare_1](https://github.com/adafruit/circuitpython/assets/22541984/ef835a61-74a1-4864-a943-f87cc5faad07)

![matrix_spare_1_hardware](https://github.com/adafruit/circuitpython/assets/22541984/2f5ef622-e62d-4ebc-8876-aa683edbe279)

![matrix_spare_2](https://github.com/adafruit/circuitpython/assets/22541984/3a938ebe-090e-4303-97b8-1ee49f065948)

![matrix_spare_2_hardware](https://github.com/adafruit/circuitpython/assets/22541984/a3df310e-499e-4a05-8f21-93fa02e99cdc)

**Comment by dhalbert** [comment]
@phantomsixthplayer Could you show a picture of your wiring from the Grand Central to the panel, and a bird's-eye view of the back so we can see all the inter-panel jumpers?

**Comment by dhalbert** [comment]
@PaintYourDragon For tuning the number of NOP's (or whatever), looks like the CBZ and CBNZ instructions (short forward conditional jumps) and the somewhat weird IT (If-Then) instruction might help. I am not at all sure of how the timings on IT work out.

**Comment by phantomsixthplayer** [comment]
I tried the other two panels I have and have the same issue.

> @phantomsixthplayer Could you show a picture of your wiring from the Grand Central to the panel, and a bird's-eye view of the back so we can see all the inter-panel jumpers?

I have labelled the components that are connected when I recorded the video.

![birds_eye](https://github.com/adafruit/circuitpython/assets/22541984/77e1166d-79e2-4aed-9a6a-f79d4142c157)

**Comment by dhalbert** [comment]
@PaintYourDragon Do you think Protomatter 1.6.1 will address this, or is it still to be debugged?
@phantomsixthplayer #8376 _may_ help this.

**Comment by PaintYourDragon** [comment]
I’m about 90% confident this should fix it, yes.

**Comment by phantomsixthplayer** [comment]
@dhalbert @PaintYourDragon 

With adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.5.uf2 there is somewhat an image now, however still an issue. The adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.2.uf2 is still the working release.

https://github.com/adafruit/circuitpython/assets/22541984/7c8b24eb-db47-421a-b248-2efa69533ba0

**Comment by PaintYourDragon** [comment]
I can replicate on test hardware here: Matrix Portal M4. Don’t even need to run code…issue is visible in the REPL display.

This is a photo of 8.2.5 but it’s basically the same as what’s seen w/8.2.2:
![matrix-circuitpython](https://github.com/adafruit/circuitpython/assets/887611/fcec2e98-1f3b-4c89-b3d4-0313f5933728)

Meanwhile, an Arduino example w/current Protomatter lib (1.6.1), rock steady:
![matrix-arduino](https://github.com/adafruit/circuitpython/assets/887611/74ded7e4-c612-4bb5-a953-13661a67beb0)
…which is weird because CircuitPython should be working with that identical code now.

Here are some scope traces…

CircuitPython **8.2.2** showing clock period in Hz, ns, and duty cycle high time in ns:
![duty-822-hz](https://github.com/adafruit/circuitpython/assets/887611/354719f7-69d7-48bf-883d-f3dde1b06b0d)
![duty-822-period](https://github.com/adafruit/circuitpython/assets/887611/d0d74ec6-cd3c-4d3c-a310-6a9a0cc8bce6)
![duty-822-hi](https://github.com/adafruit/circuitpython/assets/887611/0fd02a2e-4c1b-4d1c-82ee-10fd6e7b58b0)

CircuitPython **8.2.5** clock period in Hz, ns, duty cycle high time in ns:
![duty-825-hz](https://github.com/adafruit/circuitpython/assets/887611/980017f1-6982-4f92-90fb-a3db485b732b)
![duty-825-period](https://github.com/adafruit/circuitpython/assets/887611/71926aa5-14df-4dbd-b963-397d2b277dc8)
![duty-825-hi](https://github.com/adafruit/circuitpython/assets/887611/efe77409-403a-4a66-90fc-7125f29b0f41)

Arduino Protomatter **1.6.1** clock period in Hz, ns, duty cycle high time in ns:
![duty-arduino-hz](https://github.com/adafruit/circuitpython/assets/887611/8fe1644c-75cd-4861-81cd-2e2d9a99b070)
![duty-arduino-period](https://github.com/adafruit/circuitpython/assets/887611/0c3951cb-32c2-4feb-8019-96120216490e)
![duty-arduino-hz](https://github.com/adafruit/circuitpython/assets/887611/6808feaa-160b-4768-91cb-b80f05689eb5)

The 8.2.5 timing is especially strange because this code is _supposed_ to be cycle-counting…it shouldn’t even be possible for the clock period to be that short. This leads me to believe that compiler differences from the Arduino sketch to a CircuitPython build are causing unexpected optimizations in the latter case; that the inner loop is not the same in both environments.

I can try using inline assembly for the innermost loop so the compiler stays out of the discussion and this _should_ yield identical results for both. My asm() fu is weak and this might take me some trial and error, but I think it’s a viable and shorter approach.

Alternative is to try a thing with DMA channels and a timer but this would take substantially more work with no guarantee of success.

**Comment by PaintYourDragon** [comment]
Minor updatelet: looks like Arduino and CircuitPython are both compiling with -Os, but with Arduino using GCC 9.2.1 and CircuitPython using 10.2.1…so there might be differences in the generated code.

As a quick last-ditch thing, I’ve declared certain vars as volatile in the innermost loop. This _should_ prevent the optimizer from removing those lines. Confirmed on scope that Arduino timing is unchanged. As an alternative, in CircuitPython, exposing the duty cycle setter (_PM_setDuty()) might also prevent these lines getting optimized out (gcc gets smarter every day and will recognize things as constant even when they’re way off on another planet).

Anyway, the volatile change is already merged in the main branch of Protomatter, but I can’t bump the release number right now due to something being broken in CI (nothing in the Protomatter code itself). I will continue periodically poking this with sticks today until the logjam is hopefully fixed.

**Comment by PaintYourDragon** [comment]
Here’s a CircuitPython build (thanks @dhalbert!) with the 'volatile' change — and the timing is looking correct now both on matrix and on scope. Let me know if this clears things up. If so, it’ll go in the next release, alongside other fixes.
[firmware.uf2.zip](https://github.com/adafruit/circuitpython/files/12562793/firmware.uf2.zip)

**Comment by PaintYourDragon** [comment]
FYI if that does become necessary, a named argument in the constructor is sufficient; does not require willy-nilly set/get. _PM_setDuty() accepts an integer from 0 to _PM_maxDuty (check is probably unnecessary, the C setter clips values).

**Comment by phantomsixthplayer** [comment]
@PaintYourDragon when I tried to install the firmware, the circuitpython board is borked.

![image](https://github.com/adafruit/circuitpython/assets/22541984/4c83f73c-6b16-4ef7-b57a-16e895977380)

**Comment by PaintYourDragon** [comment]
OOF, quite right. I apologize, had my wires (figuratively) crossed.
Writing the Grand Central CircuitPython 8.2.2 or 8.2.5 firmware should revive it, it’ll just still have the wonky matrix timing until we have an updated version for that board.

**Comment by dhalbert** [comment]
@phantomsixthplayer 
Here is a similar build with the fix for Grand Central M4:
[gc4-rgbmatrix-fix.uf2.zip](https://github.com/adafruit/circuitpython/files/12564188/gc4-rgbmatrix-fix.uf2.zip)

**Comment by phantomsixthplayer** [comment]
Thanks @dhalbert and @PaintYourDragon please see the video for the results.

https://github.com/adafruit/circuitpython/assets/22541984/ffc484ce-1712-4e45-8c07-64e28fb9ab01

**Comment by dhalbert** [comment]
@phantomsixthplayer Well, that is weird. Are you able to easily try various versions of the Protomatter Arduino library? There are examples: https://github.com/adafruit/Adafruit_Protomatter/tree/master/examples. Try 1.6.0, 1.5.10, 1.5.9.

**Comment by PaintYourDragon** [comment]
At this point I think it’s gonna require exposing the duty cycle setting. 8.2.2 and this test version have an identical clock period, only the duty is different (~50% in new code, ~75% in 8.2.2). Newer matrices really prefer the 50% duty.

**Comment by phantomsixthplayer** [comment]
@dhalbert @PaintYourDragon tested arduino [simple.ino](https://github.com/adafruit/Adafruit_Protomatter/tree/master/examples/simple), seems to work properly.

```
#if defined(ADAFRUIT_GRAND_CENTRAL_M4)
  uint8_t rgbPins[]  = {8, 9, 10, 11, 12, 13};
  uint8_t addrPins[] = {4, 6, 3, 5};
  uint8_t clockPin   = 1;
  uint8_t latchPin   = 2;
  uint8_t oePin      = 0;
```

![image](https://github.com/adafruit/circuitpython/assets/22541984/84c944d1-3609-4716-be35-935b20c90c8b)
![image](https://github.com/adafruit/circuitpython/assets/22541984/c19aebdc-21f1-4783-9563-334680f3bc79)

https://github.com/adafruit/circuitpython/assets/22541984/140dae6c-ea44-4e2d-9668-59cdea471767

**Comment by PaintYourDragon** [comment]
Scope trace, special CircuitPython build:
![clock-cp](https://github.com/adafruit/circuitpython/assets/887611/3e6fa58c-e40b-4784-9120-8ae321957392)

Same, Arduino lib 1.6.2:
![clock-arduino](https://github.com/adafruit/circuitpython/assets/887611/1afc2bfc-5a88-4261-a729-0511e6f604ac)

The timing is _identical,_ down to the clock cycle, even the every-8th-bit delay. I cannot explain why this would work with the Arduino library and not with CircuitPython _built against the same code and generating the same clock signal, and on the same hardware._ Defies all explanation. I am out of ideas and probably unfit for my job.

**Comment by PaintYourDragon** [comment]
Does CircuitPython do anything with the pin drive strength? Arduino on SAMD always sets PORT_PINCFG_DRVSTR (stronger drive strength) on all GPIO. If this is not the default behavior of CircuitPython, perhaps it could be added to the _PM_pinOutput macro so it’s applied to all Protomatter pins.

**Comment by PaintYourDragon** [comment]
Drive strength theory might also explain why either works on Matrix Portal; that board has level-shifted outputs.

If the Grand Central circuit lacks level shifting…drive strength might work _just well enough_ to get it working in this situation, but we really really highly extremely discourage controlling these matrices from 3.3V logic.

**Comment by dhalbert** [comment]
> Does CircuitPython do anything with the pin drive strength? Arduino on SAMD always sets PORT_PINCFG_DRVSTR (stronger drive strength) on all GPIO. If this is not the default behavior of CircuitPython, perhaps it could be added to the _PM_pinOutput macro so it’s applied to all Protomatter pins.

CircuitPython does not do anything with the pins except pass them on to `_PM_init()`. It _does_ use high drive strength for `DigitalInOut`, but not for RGBMatrix.

**Comment by PaintYourDragon** [comment]
OK @phantomsixthplayer, here’s a quick-n-dirty thing to try. Add this before declaring the matrix:
```
for pin in [ board.D8, board.D9, board.D10, board.D11, board.D12, board.D13, board.D4, board.D6, board.D3, board.D5, board.D1, board.D2, board.D0 ]:
    foo = digitalio.DigitalInOut(pin)
    foo.direction = digitalio.Direction.OUTPUT
    foo.deinit()
```
From what I can tell, looks like deinit() doesn’t reset a pin’s drive strength. So _in theory_ this will set each pin to high strength and then release it so rgbmatrix can use it in that enbeefened state.

**Comment by phantomsixthplayer** [comment]
@PaintYourDragon 

adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.5.uf2

```
displayio.release_displays()

for pin in [ board.D8, board.D9, board.D10, board.D11, board.D12, board.D13, board.D4, board.D6, board.D3, board.D5, board.D1, board.D2, board.D0 ]:
    foo = digitalio.DigitalInOut(pin)
    foo.direction = digitalio.Direction.OUTPUT
    foo.deinit()
    
matrix = rgbmatrix.RGBMatrix(
    width=64,
    height=32,
    bit_depth=4,
    rgb_pins=[board.D8, board.D9, board.D10, board.D11, board.D12, board.D13],
    addr_pins=[board.D4, board.D6, board.D3, board.D5],
    clock_pin=board.D1,
    latch_pin=board.D2,
    output_enable_pin=board.D0
)
display = framebufferio.FramebufferDisplay(matrix)
```

With or without the added code it gives the same result

https://github.com/adafruit/circuitpython/assets/22541984/c3283e4c-8a66-44e5-9826-2acebc110d44

**Comment by phantomsixthplayer** [comment]
This is the order I uploaded the firmware:
adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.2.uf2
adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.3.uf2
adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.4.uf2
adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.5.uf2
gc4-rgbmatrix-fix.uf2

```
import displayio
import rgbmatrix
import board
import framebufferio
from adafruit_bitmap_font import bitmap_font
from adafruit_display_text.label import Label
import digitalio
import busio
import sdcardio
import storage
import adafruit_debouncer

displayio.release_displays()

for pin in [ board.D8, board.D9, board.D10, board.D11, board.D12, board.D13, board.D4, board.D6, board.D3, board.D5, board.D1, board.D2, board.D0 ]:
    foo = digitalio.DigitalInOut(pin)
    foo.direction = digitalio.Direction.OUTPUT
    foo.deinit()
    
matrix = rgbmatrix.RGBMatrix(
    width=64,
    height=32,
    bit_depth=4,
    rgb_pins=[board.D8, board.D9, board.D10, board.D11, board.D12, board.D13],
    addr_pins=[board.D4, board.D6, board.D3, board.D5],
    clock_pin=board.D1,
    latch_pin=board.D2,
    output_enable_pin=board.D0
)
display = framebufferio.FramebufferDisplay(matrix)

font = bitmap_font.load_font("/fonts/test.pcf")

mg = displayio.Group()
mg_a = Label(font, text="A.A.A.A", color=0x00FF00, x=15, y=6)
mg_h = Label(font, text="H.H.H.H", color=0x00FF00, x=14, y=17)
mg_b = Label(font, text="B.B.B.B", color=0x00FF00, x=15, y=28)
mg.append(mg_a)
mg.append(mg_h)
mg.append(mg_b)

while True:
    display.show(mg)
```

https://github.com/adafruit/circuitpython/assets/22541984/5066d154-fe7d-4f20-a5e0-0e015dc659e0

**Comment by PaintYourDragon** [comment]
OK. I can’t be certain whether CircuitPython is fully resetting the pin on deinit(), it was just a quick hack to try in that it _might_ have left high-drive enabled. CircuitPython is big and I’m not deeply involved in it.

Regardless…without level shifting in the circuit, this is a design problem, not a software bug. That it showed some success in a prior release is “stars aligning” and not an engineered solution. I’ll spend a little more time and see if I can work drive strength into the library without breaking CircuitPython, but this is a band-aid at best.

**Comment by phantomsixthplayer** [comment]
If I was to buy another matrix from digikey how can I be sure I won't get the 'old' revision matrix that doesn't support the ~50% in duty cycle update. I got unlucky and got three of them lol. I guess another solution is to rewrite the entire CirciutPython application in Arduino which would solve it as well.

**Comment by PaintYourDragon** [comment]
I think the new/old matrix thing is a red herring. We can try to make the duty cycle configurable. We can try to boost the drive strength. But without level shifting, all that might _seem_ like it’s fixed, but the temperature swings 20 degrees and things inexplicably go haywire because it was all a lucky edge case.

**Comment by bluelasers** [comment]
You are aware of the flash access time limits? You are aware of the RAM arbitration limits? 

There is no real way to count cycles in cooperative 32-bit processor beyond 25-50MHz in most that I have seen. Closest you can do is with RAM function using bus arbitration promoting CPU. (Variable CPI, like Von Neumann and like Harvard.)

Protomatter belongs on dedicated processor. I would presume CircuitPython will ditch Protomatter eventually or recommend against it. This would allow better central management independent of CircuitPython. This would also allow crazy bit banging schemes. This also allows for better features, but I mum is the word on that.

If drive strength is the issue you should see it in scope at end of chain. Look at rise/fall times (skew rates). This is hardware issue and should be corrected with documentation.

How does Os behave again?

**Comment by bluelasers** [comment]
You are aware of the flash access time limits? You are aware of the RAM arbitration limits?

There is no real way to count cycles in cooperative 32-bit processor beyond 25-50MHz in most that I have seen. Closest you can do is with RAM function using bus arbitration promoting CPU. (Variable CPI, like Von Neumann and like Harvard.)

Protomatter belongs on dedicated processor. I would presume CircuitPython will ditch Protomatter eventually or recommend against it. This would allow better central management independent of CircuitPython. This would also allow crazy bit banging schemes. This also allows for better features, but mum is the word on that.

If drive strength is the issue you should see it in scope at end of chain. Look at rise/fall times (skew rates). This is hardware issue and should be corrected with documentation.

How does Os behave again?

**Comment by bluelasers** [comment]
How stable is the power rail? How stable is the cable signals? (Ringing, load capacitance, etc.) Temperature and power can mess with it. (Look at the end of the chain to see the truth. This is what the drivers saw.)

**Comment by PaintYourDragon** [comment]
@dhalbert I’ve added some code in arch/samd51.h that _in theory_ enables high drive mode on all Protomatter pins (static function _hi_drive()).

HOWEVER…it makes an assumption about pin numbers that might not be correct. I’ve dug a few layers down into CircuitPython source but you could probably answer this in like 12 seconds…

I don’t know how pin indices (as stored in the core structure) map to hardware in CircuitPython…whether it’s fairly direct or if these go through a table (as in Arduino, where there’s a PORT/bit lookup involved). Right now the code’s assuming direct, i.e. pin indices to PORT/bit would resemble:
0–31 = PORTA00–PORTA31, 32-63 = PORTB00–PORTB31, 64–95 = PORTC00–PORTC31, etc.

If remapping takes place, directions to said map would be helpful. If there’s no remapping and the pins work like above, then the new code should work as-in. (Tested and does “work” on Arduino, though that already uses high drive by default, I just mean it doesn’t crash & burn at that step.) Thanks much.

**Comment by dhalbert** [comment]
@PaintYourDragon The pin numbers are the actual numbers. The remapping is at the pin name level. So this should work. I will try to do some testing.

**Comment by dhalbert** [comment]
@phantomsixthplayer I duplicated your setup, more or less:
- Grand Central M4
- Exactly the same pins as you are using; no outboard level shifting (3.3v pins)
- power (only) supplied via MatrixPortal S3 panel power screw terminals and cable, so panel power is from a second USB port
- Same font display test program that you supply above. Also tried a [scrolling text program](https://learn.adafruit.com/rgb-led-matrices-matrix-panels-with-circuitpython/example-simple-two-line-text-scroller).

I am testing this on a 64x32 3mm pitch panel I got in October 2020, so not such recent vintage.

I tested with CircuitPython 8.2.2 and 8.2.5. For both test programs, I had a stable display. I could not reproduce your instability.

I then built the latest trial from @PaintYourDragon, which forces high drive strength. That worked fine also. Here is the UF2 for that build for you to try: 
[gc4-rgbmatrix-fix.uf2.zip](https://github.com/adafruit/circuitpython/files/12580716/gc4-rgbmatrix-fix.uf2.zip)

This is kind of the last thing to try that we can think of. I guess you might consider building a pluggable level shifter at some point if you don't want to redo the board.

**Comment by phantomsixthplayer** [comment]
@dhalbert thanks for testing. I still get an issue. I'll stay on adafruit-circuitpython-grandcentral_m4_express-en_GB-8.2.2.uf2 until I learn arduino and port it over

**Comment by dhalbert** [comment]
I will close this because it seems the problem is fundamentally missing level-shifting. @phantomsixthplayer thanks for all your testing.

**Comment by jepler** [comment]
fwiw I received a feedback on Learn that some RGB Matrix project, possibly the ["two line" scroller](https://learn.adafruit.com/admin/guides/2976/editor/19232) isn't working in any stable version since 8.2.2:
> The example programs appear to not work with circuitpython versions after 8.2.2. The issue is discussed here: https://github.com/adafruit/circuitpython/issues/8303
>
> I spent days trying to get the examples to work with circuitpython 8.2.7. I was only able to get them to work once I went back to version 8.2.2. With that older version they work like a dream!

The feedback did not give information about what specific boards/products were used, so it's impossible to know if this is the "sigh, doesn't look like it's going to work, but we don't understand why" problem on some boards without level shifting, or whether it's something else.

**Comment by phantomsixthplayer** [comment]
@dhalbert just wanted to update you that I tried the latest Circuit Python version 9 and the matrix worked with the sample [2 line scrolling](https://learn.adafruit.com/rgb-led-matrices-matrix-panels-with-circuitpython/example-simple-two-line-text-scroller) but when I used my code I ended getting memory allocation errors and an issue with sdcardio, understanding that its in beta, will check back in other revisions.

**Comment by phantomsixthplayer** [comment]
If anyone else was had this issue can confirm from 'adafruit-circuitpython-grandcentral_m4_express-en_GB-9.0.4' everything for my application is working as before on 8.2.2 so fingers crossed yours is too!
